shared:
  ingress_domain: "shared.homelab.tanzu"
  ingress_issuer: "tap-ingress-selfsigned" # Optional, can denote a cert-manager.io/v1/ClusterIssuer of your choice. Defaults to "tap-ingress-selfsigned".
  image_registry:
    project_path: "hl-harbor.homelab.tanzu/hl-projects/build-service"
    secret:
      name: "kp-default-repository-creds"
      namespace: "tap-install"
  ca_cert_data: |
    -----BEGIN CERTIFICATE-----
    MIIFsTCCA5mgAwIBAgIUSPcih3pZhoz14WlFJ1epieB5VuwwDQYJKoZIhvcNAQEN
    BQAwaDELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAktBMQwwCgYDVQQHDANCTFIxDDAK
    BgNVBAoMA1ZNVzEOMAwGA1UECwwFTUFNQkcxIDAeBgNVBAMMF2hsLWhhcmJvci5o
    b21lbGFiLnRhbnp1MB4XDTIzMDYwNjE2MzQ1NVoXDTMzMDYwMzE2MzQ1NVowaDEL
    MAkGA1UEBhMCSU4xCzAJBgNVBAgMAktBMQwwCgYDVQQHDANCTFIxDDAKBgNVBAoM
    A1ZNVzEOMAwGA1UECwwFTUFNQkcxIDAeBgNVBAMMF2hsLWhhcmJvci5ob21lbGFi
    LnRhbnp1MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuk+RafZ6zBZf
    LFT16zKnXs9glOqkhIJG3Qwiq278YgKbDkhHeURD7SSBm/pQpJkN/r9RWioYPnEy
    sMytiLmxblf42dMX6TJIuLtpwo6kL+WYFEXP8MKMi8Kg8M1LYPQkKEZu4pob/3wF
    x60lMoZmxk1FPvvsRffvitHIyjefJRUNVrCUNFrllqmQwz/N5RDt8MNPdH5qbSrB
    GWTsNk2Yrc7OFL0ChFd/B1TLX5Usl3oEHqwYNB8p0igt0Lj7I2TFxC4VDq6dPEcC
    uchT2nVpnMBp9M730XB4Djd8ZgGIWi7sjm04Tpb/wkeM8BljPcJ435QwjR4u2dJQ
    lCTMp745NZPtZ1ATcfXxt9r/7k8aUGKem6xMx9IALsujucPjhnr+K/9QtenASFFU
    9OJSECt6nrUuBq7u4eKds3tKQ+HePf8ft66OnQ0bD4KFz/0pb+USwP3GZjtibgy6
    /jvqK3+/MmUMW/ZWjeq8zcI2CoB7uue5okrGI3cgAulrcIvpzQPOH1W/g0YwjUs+
    1bsdR3eX0LLrgYyAbpzjBlGjpReJdHNSNGnNGJrnq1OuXsyGVZVmDgJEm2O4boUJ
    IV1P+Byhofey2dh5k8k++t+nnw/FEN1ir6eaSs33je4D7/bWkXZ8qqhqCfJQz3eu
    cJvynbzhzGfV584WH0OsvoQzMx6HgLECAwEAAaNTMFEwHQYDVR0OBBYEFDEWl+ph
    ZzEC3XD/XomtWsJwKWTgMB8GA1UdIwQYMBaAFDEWl+phZzEC3XD/XomtWsJwKWTg
    MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQENBQADggIBAG0yk3i7M5FuMSOw
    +ywV+hiRCZWl5hYhjsOB5fKt+/ngMZ2G+MtXjiJzTqzceQctEun5cymWY83Q3YHW
    aauHCu3ygsg2MpWlLQiGZvTVqrQfc5024m3pScn+NTbcCUUhAcG+elxmQhKF4BnZ
    hETkqR2Mo4PUL6kNlNBib/UtDUQGkvOLIt4fd06tp8PbqvEg8fdUaCxc8qZunBWF
    aoLxlqRFIaPAyQQtIfqPd+HO8CFyfMyYOm7q//DPDmFebpE98Hg62M017og14fYz
    3nbarH6+nuQUIdcNUWOc0IJk5Ry5Ssk8xlJeACgqoG3JIUYLWoy5qEaVzIXOusFq
    uwO7dzPhrLci3VTdGJe8GSoRfzdM+wB6Le35NmpasgK2Fx4NxLwcXl293Xbsfyil
    EktnrDBG9xfepKMt++iFYd22JrL4kbHPacFOeKzwNlbm8qqfRMr8SlTZi9qYxO7P
    DPS3QwOvGtLIoz5inkH7WtkzKZm3VkyniH7wzHAv5xRAx0vHq3jpWCSxPldvuykr
    6yBIVGtfpOHGwZBNdW0cPGejJtKLzWW/uExTZQ/fLkeI7qI9vCRF8Ic0KvJar9pH
    1ZZaSMHqmKS9Wmc9sW6TPdXCRwAZHMkl5VPSvb1MJUhGTUHcGu5hMoUiVUx975Ql
    v84oKMqo1ajqLNPFA2banVVXNGDQ
    -----END CERTIFICATE-----
  kubernetes_distribution: "" # Only required if the distribution is OpenShift and must be used with the following kubernetes_version key.

  kubernetes_version: "1.25.7" # Required regardless of distribution when Kubernetes version is 1.25 or later.

    ## ca_cert_data: | # To be passed if using custom certificates.
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

#The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

#Below are the keys which may have default values set, but can be overridden.

profile: full # Can take iterate, build, run, view.
  ## excluded_packages:
supply_chain: basic # Can take testing, testing_scanning.

ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
  registry:
    server: "hl-harbor.homelab.tanzu" # Takes the value from the shared section by default, but can be overridden by setting a different value.
    repository: "hl-projects" # Takes the value from the shared section by default, but can be overridden by setting a different value.
  gitops:
    ssh_secret: " " # Takes "" as value by default; but can be overridden by setting a different value.

contour:
  envoy:
    service:
      type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

buildservice:
  # Takes the value from the shared section by default, but can be overridden by setting a different value.
  kp_default_repository: "hl-harbor.homelab.tanzu/hl-projects/build-service"
  kp_default_repository_secret:  # Takes the value from the shared section above by default, but can be overridden by setting a different value.
    name: "kp-default-repository-creds"
    namespace: "tap-install"
  ca_cert_data: |
    -----BEGIN CERTIFICATE-----
    MIIFsTCCA5mgAwIBAgIUSPcih3pZhoz14WlFJ1epieB5VuwwDQYJKoZIhvcNAQEN
    BQAwaDELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAktBMQwwCgYDVQQHDANCTFIxDDAK
    BgNVBAoMA1ZNVzEOMAwGA1UECwwFTUFNQkcxIDAeBgNVBAMMF2hsLWhhcmJvci5o
    b21lbGFiLnRhbnp1MB4XDTIzMDYwNjE2MzQ1NVoXDTMzMDYwMzE2MzQ1NVowaDEL
    MAkGA1UEBhMCSU4xCzAJBgNVBAgMAktBMQwwCgYDVQQHDANCTFIxDDAKBgNVBAoM
    A1ZNVzEOMAwGA1UECwwFTUFNQkcxIDAeBgNVBAMMF2hsLWhhcmJvci5ob21lbGFi
    LnRhbnp1MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuk+RafZ6zBZf
    LFT16zKnXs9glOqkhIJG3Qwiq278YgKbDkhHeURD7SSBm/pQpJkN/r9RWioYPnEy
    sMytiLmxblf42dMX6TJIuLtpwo6kL+WYFEXP8MKMi8Kg8M1LYPQkKEZu4pob/3wF
    x60lMoZmxk1FPvvsRffvitHIyjefJRUNVrCUNFrllqmQwz/N5RDt8MNPdH5qbSrB
    GWTsNk2Yrc7OFL0ChFd/B1TLX5Usl3oEHqwYNB8p0igt0Lj7I2TFxC4VDq6dPEcC
    uchT2nVpnMBp9M730XB4Djd8ZgGIWi7sjm04Tpb/wkeM8BljPcJ435QwjR4u2dJQ
    lCTMp745NZPtZ1ATcfXxt9r/7k8aUGKem6xMx9IALsujucPjhnr+K/9QtenASFFU
    9OJSECt6nrUuBq7u4eKds3tKQ+HePf8ft66OnQ0bD4KFz/0pb+USwP3GZjtibgy6
    /jvqK3+/MmUMW/ZWjeq8zcI2CoB7uue5okrGI3cgAulrcIvpzQPOH1W/g0YwjUs+
    1bsdR3eX0LLrgYyAbpzjBlGjpReJdHNSNGnNGJrnq1OuXsyGVZVmDgJEm2O4boUJ
    IV1P+Byhofey2dh5k8k++t+nnw/FEN1ir6eaSs33je4D7/bWkXZ8qqhqCfJQz3eu
    cJvynbzhzGfV584WH0OsvoQzMx6HgLECAwEAAaNTMFEwHQYDVR0OBBYEFDEWl+ph
    ZzEC3XD/XomtWsJwKWTgMB8GA1UdIwQYMBaAFDEWl+phZzEC3XD/XomtWsJwKWTg
    MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQENBQADggIBAG0yk3i7M5FuMSOw
    +ywV+hiRCZWl5hYhjsOB5fKt+/ngMZ2G+MtXjiJzTqzceQctEun5cymWY83Q3YHW
    aauHCu3ygsg2MpWlLQiGZvTVqrQfc5024m3pScn+NTbcCUUhAcG+elxmQhKF4BnZ
    hETkqR2Mo4PUL6kNlNBib/UtDUQGkvOLIt4fd06tp8PbqvEg8fdUaCxc8qZunBWF
    aoLxlqRFIaPAyQQtIfqPd+HO8CFyfMyYOm7q//DPDmFebpE98Hg62M017og14fYz
    3nbarH6+nuQUIdcNUWOc0IJk5Ry5Ssk8xlJeACgqoG3JIUYLWoy5qEaVzIXOusFq
    uwO7dzPhrLci3VTdGJe8GSoRfzdM+wB6Le35NmpasgK2Fx4NxLwcXl293Xbsfyil
    EktnrDBG9xfepKMt++iFYd22JrL4kbHPacFOeKzwNlbm8qqfRMr8SlTZi9qYxO7P
    DPS3QwOvGtLIoz5inkH7WtkzKZm3VkyniH7wzHAv5xRAx0vHq3jpWCSxPldvuykr
    6yBIVGtfpOHGwZBNdW0cPGejJtKLzWW/uExTZQ/fLkeI7qI9vCRF8Ic0KvJar9pH
    1ZZaSMHqmKS9Wmc9sW6TPdXCRwAZHMkl5VPSvb1MJUhGTUHcGu5hMoUiVUx975Ql
    v84oKMqo1ajqLNPFA2banVVXNGDQ
    -----END CERTIFICATE-----
tap_gui:
  metadataStoreAutoconfiguration: true # Creates a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Application Platform GUI and SCST - Store.
  app_config:
    catalog:
      locations:
        - type: url
          target: https://raw.githubusercontent.com/emailtovinod/hltap/main/catalog-info.yaml
metadata_store:
  ns_for_export_app_cert: "tap-install" # Verify this namespace is available within your cluster before initiating the Tanzu Application Platform installation.
  app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

scanning:
  metadataStore:
    url: "" # Configuration is moved, so set this string to empty.

grype:
  namespace: "tap-install" # Verify this namespace is available within your cluster before initiating the Tanzu Application Platform installation.
  targetImagePullSecret: "registry-credentials"
  # In a single cluster, the connection between the scanning pod and the metadata store happens inside the cluster and does not pass through ingress. This is automatically configured, you do not need to provide an ingress connection to the store.

policy:
  tuf_enabled: false # By default, TUF initialization and keyless verification are deactivated.
tap_telemetry:
  ## customer_entitlement_account_number: 12345
  installed_for_vmware_internal_use: true
    # (Optional) Identify data for creating the Tanzu Application Platform usage reports.
